import * as fs from "node:fs";
import * as path from "node:path";
import { writeIfChanged } from "../../util/generated-file";
import { CONTROL_ENV, CONTROL_HOST } from "../../../shared/ctl";

/**
 * Writes the extension into `agentDir` (already the agent's own, so a fixed name) and
 * returns the `-e` path. Renamed into place: a win32 read mid-write fails. Throws on a failed
 * write: pi must never get a half file. Nothing in it depends on where it runs: the control
 * channel's address is read from its env.
 */
export function writePiExtension(agentDir: string): string {
  // pi lists a local extension by its file name, or by its folder's for an index.ts:
  // `tet/index.ts` reads "tet" beside the others.
  const folder = path.join(agentDir, "tet");
  fs.mkdirSync(folder, { recursive: true });
  const file = path.join(folder, "index.ts");
  writeIfChanged(file, renderPiExtension());
  return file;
}

/**
 * The extension source; pure, so tests can compile it.
 *
 * pi loads `-e <path>` (jiti; spaces work) before the project-trust dialog and EXITS on a load
 * failure, so every branch must compile (test/main/agents.test.ts). Nothing imported from pi's
 * packages: they don't resolve under TET's data folder, and its events are plain objects.
 *
 * Event order: session_start → (per prompt) before_agent_start → agent_start → turn_start/turn_end…
 * → agent_end → agent_settled; ui_prompt_start/end around an extension's own dialogs.
 *
 * Turns are reported by its own `report(event, sessionId)`, on tet-ctl's wire contract
 * (src/shared/ctl.ts), not by a `tet-ctl` hook. node:http, not fetch: one assumption fewer about
 * pi's runtime. Never awaited: pi waits for handlers, and a mark must not hold up the TUI. The
 * payload carries the session id, which binds the tab to its session (`hookSessionId`).
 */
export function renderPiExtension(): string {
  return `// Generated by TET, read by nothing but pi. Turns are reported over
// TET's control channel (src/shared/ctl.ts).
import * as http from "node:http";

// The names only: the port and token behind them are new on every start of TET, and baking
// them in would change this file on every start.
const CONTROL = ${JSON.stringify(CONTROL_ENV)};

// This tab's own turn, reported to TET over its control channel, from inside this process.
function report(event: string, sessionId: string | undefined): void {
  const port = process.env[CONTROL.port];
  const token = process.env[CONTROL.token];
  if (!port || !token) {
    return;
  }
  const payload = JSON.stringify(sessionId ? { session_id: sessionId } : {});
  const body = JSON.stringify({
    token,
    verb: "hook",
    args: { event, payload },
    caller: {
      projectId: process.env[CONTROL.projectId],
      worktree: process.env[CONTROL.worktree] || undefined,
      tabId: process.env[CONTROL.tabId]
    },
    // Now, not when it arrives: nothing here is awaited, so two reports of one turn race.
    at: Date.now()
  });
  try {
    const request = http.request(
      {
        host: process.env[CONTROL.host] || ${JSON.stringify(CONTROL_HOST)},
        port: Number(port),
        method: "POST",
        path: "/",
        headers: { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(body), Connection: "close" }
      },
      (response: any) => response.resume()
    );
    request.on("error", () => undefined);
    request.end(body);
  } catch {
    // Nothing to tell the agent about; a missed report is a tab that has to be looked at.
  }
}

// The session a handler runs for: the transcript header's id, which ctx.sessionManager hands
// every handler.
function sessionOf(ctx: any): string | undefined {
  try {
    const sessionId = ctx?.sessionManager?.getSessionId();
    return typeof sessionId === "string" && sessionId ? sessionId : undefined;
  } catch {
    return undefined;
  }
}

export default function (pi: { on(event: string, handler: (event: any, ctx: any) => unknown): void }): void {
  // agent_start fires per low-level run — a retry or a compaction is another one, and the mark
  // is simply set again. agent_settled fires once nothing is left to run automatically, the end
  // of the turn as the tab sees it; an Escape-abort settles too. pi has no subagents, no guard.
  // \`prompt-submit\` is what a turn starting is called on the channel; its answer carries nothing.
  pi.on("agent_start", (_event, ctx) => {
    report("prompt-submit", sessionOf(ctx));
  });
  pi.on("agent_settled", (_event, ctx) => {
    report("stop", sessionOf(ctx));
  });
  // pi has no permission prompts; ui_prompt_start is an extension's own dialog, a progress view
  // (\`ui.custom\`) included, so its end clears the mark however it closed. The project-trust
  // dialog at startup is not reported — it comes before session_start.
  pi.on("ui_prompt_start", (_event, ctx) => {
    report("permission", sessionOf(ctx));
  });
  pi.on("ui_prompt_end", (_event, ctx) => {
    report("answered", sessionOf(ctx));
  });
}
`;
}
