import * as fs from "node:fs";
import * as path from "node:path";
import { HOST_TARGET, type HookTarget } from "../../terminals/hook-target";
import { CONTROL_ENV } from "../../../shared/control";

/** Everything the generated extension has baked in — written into the source as JSON literals,
 *  so nothing is ever shell-quoted. The turns it reports go over the control channel, whose
 *  address it reads from its own environment at run time. */
export interface PiExtensionOptions {
  contextFile: string;
}

/**
 * Writes this repository's extension into `storageDir` and returns the path for `-e`. One fixed
 * name is enough: `storageDir` is already per agent per project. Written beside the target and
 * renamed into place — pi reads it once at startup, and a read landing mid-write fails on
 * Windows. Throws on a failed write: pi must never be pointed at a half file.
 *
 * `target` is where the extension will *run*, host or sandbox (hook-target.ts). Only what is
 * baked into the file is translated; the writing happens here, at the paths this process sees.
 */
export function writePiExtension(storageDir: string, contextFile: string, target: HookTarget = HOST_TARGET): string {
  fs.mkdirSync(storageDir, { recursive: true });
  const file = path.join(storageDir, "tet.ts");
  const temp = `${file}.tmp`;
  fs.writeFileSync(temp, renderPiExtension({ contextFile: target.embed(contextFile) }));
  fs.renameSync(temp, file);
  return file;
}

/**
 * The extension's TypeScript source, pure so the test can check its syntax without a disk.
 *
 * pi loads it through `-e <path>` (jiti compiles the TypeScript; paths with spaces work) before
 * the project-trust dialog, and EXITS outright on one that fails to load. So every branch has to
 * stay valid, which pieces.test.ts checks by compiling it. Nothing is imported from pi's own
 * packages: they do not resolve under userData, and pi's event contract is plain objects.
 *
 * The events, in the order measured: session_start → (per prompt) before_agent_start →
 * agent_start → turn_start/turn_end… → agent_end → agent_settled; ui_prompt_start/end around an
 * extension's ctx.ui.confirm/select/input/editor/custom.
 */
export function renderPiExtension(options: PiExtensionOptions): string {
  return `// Generated by tet for one repository, read by nothing but pi. Turns are reported over
// tet's control channel (src/shared/control.ts); the context file is tet's.
import * as fs from "node:fs";
import * as http from "node:http";

const CONTEXT_FILE = ${JSON.stringify(options.contextFile)};
// The names only: the port and token behind them are new on every start of tet, and this file
// is written on every spawn — baking them in would rewrite it for no reason.
const CONTROL = ${JSON.stringify(CONTROL_ENV)};

// This tab's own turn, reported to tet: the same wire contract tet-ctl speaks, from inside this
// process rather than through it. node:http rather than fetch, which is one assumption fewer
// about the runtime pi brings. Never awaited: pi waits for a handler to return, and a turn mark
// must not hold up the TUI.
function report(event: string): void {
  const port = process.env[CONTROL.port];
  const token = process.env[CONTROL.token];
  if (!port || !token) {
    return;
  }
  const body = JSON.stringify({
    token,
    verb: "hook",
    args: { event },
    caller: { projectId: process.env[CONTROL.projectId], tabId: process.env[CONTROL.tabId] }
  });
  try {
    const request = http.request(
      {
        host: process.env[CONTROL.host] || "127.0.0.1",
        port: Number(port),
        method: "POST",
        path: "/",
        headers: { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(body), Connection: "close" }
      },
      (response: any) => response.resume()
    );
    request.on("error", () => undefined);
    request.end(body);
  } catch {
    // Nothing to tell pi about; a missed report is a tab that has to be looked at.
  }
}

export default function (pi: { on(event: string, handler: (event: any, ctx: any) => unknown): void }): void {
  // The context file's contents go at the end of the system prompt, which is where a returned
  // systemPrompt lands in the request (measured). Read on every prompt, since tet keeps the file
  // current. On win32 it carries a BOM (shell-context.ts), stripped so it never reaches the model.
  pi.on("before_agent_start", (event) => {
    let text = "";
    try {
      text = fs.readFileSync(CONTEXT_FILE, "utf8").replace(/^\\uFEFF/, "").trim();
    } catch {
      return undefined;
    }
    if (!text) {
      return undefined;
    }
    const base = typeof event.systemPrompt === "string" ? event.systemPrompt : "";
    return { systemPrompt: base + "\\n\\n" + text };
  });
  // agent_start fires per low-level run — a retry or a compaction is another one, and the mark
  // is simply set again. agent_settled fires once nothing is left to run automatically, the end
  // of the turn as the tab sees it; an Escape-abort settles too. pi has no subagents, no guard.
  // \`prompt-submit\` is what a turn starting is called on the channel; pi takes the context file
  // itself, above, so it has no use for what the answer carries.
  pi.on("agent_start", () => {
    report("prompt-submit");
  });
  pi.on("agent_settled", () => {
    report("stop");
  });
  // pi has no permission prompts; ui_prompt_start is an extension's own dialog. The project-trust
  // dialog at startup is not reported — it comes before session_start.
  pi.on("ui_prompt_start", () => {
    report("permission");
  });
}
`;
}
