import * as fs from "node:fs";
import * as path from "node:path";
import { writeIfChanged } from "../../write-if-changed";
import { renderHookReport } from "../hook-report";

/**
 * Writes the extension into `storageDir` (already per agent per project, so a fixed name) and
 * returns the `-e` path. Renamed into place: a win32 read mid-write fails. Throws on a failed
 * write: pi must never get a half file. Nothing in it depends on where it runs: the control
 * channel's address is read from its env.
 */
export function writePiExtension(storageDir: string): string {
  // pi lists a local extension by its file name, or by its folder's for an index.ts (measured,
  // 0.85.1): `tet/index.ts` reads "tet" beside the others, where `tet.ts` read "tet.ts".
  const folder = path.join(storageDir, "tet");
  fs.mkdirSync(folder, { recursive: true });
  const file = path.join(folder, "index.ts");
  writeIfChanged(file, renderPiExtension());
  return file;
}

/**
 * The extension source; pure, so tests can compile it.
 *
 * pi loads `-e <path>` (jiti; spaces work) before the project-trust dialog and EXITS on a load
 * failure, so every branch must compile (pieces.test.ts). Nothing imported from pi's packages:
 * they don't resolve under tet's data folder, and its events are plain objects.
 *
 * Measured event order: session_start → (per prompt) before_agent_start → agent_start →
 * turn_start/turn_end… → agent_end → agent_settled; ui_prompt_start/end around an extension's
 * ctx.ui.confirm/select/input/editor/custom.
 */
export function renderPiExtension(): string {
  return `// Generated by tet for one repository, read by nothing but pi. Turns are reported over
// tet's control channel (src/shared/control.ts).
import * as http from "node:http";

${renderHookReport("pi")}

// The session a handler runs for: the transcript header's id, which ctx.sessionManager hands
// every handler (0.85.1).
function sessionOf(ctx: any): string | undefined {
  try {
    const sessionId = ctx?.sessionManager?.getSessionId();
    return typeof sessionId === "string" && sessionId ? sessionId : undefined;
  } catch {
    return undefined;
  }
}

export default function (pi: { on(event: string, handler: (event: any, ctx: any) => unknown): void }): void {
  // agent_start fires per low-level run — a retry or a compaction is another one, and the mark
  // is simply set again. agent_settled fires once nothing is left to run automatically, the end
  // of the turn as the tab sees it; an Escape-abort settles too. pi has no subagents, no guard.
  // \`prompt-submit\` is what a turn starting is called on the channel; its answer carries nothing.
  pi.on("agent_start", (_event, ctx) => {
    report("prompt-submit", sessionOf(ctx));
  });
  pi.on("agent_settled", (_event, ctx) => {
    report("stop", sessionOf(ctx));
  });
  // pi has no permission prompts; ui_prompt_start is an extension's own dialog. The project-trust
  // dialog at startup is not reported — it comes before session_start.
  pi.on("ui_prompt_start", (_event, ctx) => {
    report("permission", sessionOf(ctx));
  });
}
`;
}
