import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { CONTROL_ENV } from "../../../shared/control";
import type { HookTarget } from "../../terminals/hook-target";

/**
 * opencode is driven through one generated plugin per repository: a `.ts` file under a config
 * directory's `plugins/`, loaded in-process by the `opencode` the tab runs. It has no declarative
 * hook file; the plugin API is the one way into a message being composed (`chat.message`) and,
 * through the server's whole event bus (`event`), the one place every turn signal can be read.
 * Measured against 1.18.4 on the host and 1.18.23 in an sbx sandbox: the `event` hook receives
 * `session.created`, `session.updated` (with the whole session), `session.status`,
 * `session.idle`, `permission.asked`/`replied` and `question.asked` exactly as `/event` does.
 *
 * `OPENCODE_CONFIG_DIR` points opencode at the directory additively; it does not replace the
 * user's own `plugins/`. The first time opencode sees a `plugins/` file in a config dir it
 * bun-installs `@opencode-ai/plugin` *into that dir* (measured), taking seconds to minutes — so
 * the host's dir is shared across repositories and a sandbox gets a Linux one under agentDir.
 */

/** What one repository's plugin is baked with — see the header. The turns it reports go over the
 *  control channel, whose address it reads from its own environment at run time. */
export interface OpencodePluginOptions {
  /** The repository's root as the plugin's own process sees it — the `TET_PROJECT_ROOT` guard. */
  projectRoot: string;
  contextFile: string;
  /** Where a session record goes (sessions/<id>.json) and where a rename request is found. */
  sessionsDir: string;
  renameDir: string;
  /** The sbx sandbox this plugin runs in, recorded on every session; null on the host. */
  sandbox: string | null;
}

/** Set on the tab's process so the generated plugin can tell whose repository it is serving. */
export const PROJECT_ROOT_ENV = "TET_PROJECT_ROOT";

/** The record one session leaves under sessionsDir — what the listing reads. */
export interface SessionRecord {
  id: string;
  title: string;
  created: number;
  updated: number;
  sandbox: string | null;
}

/** A sandboxed tab's plugin lives in its own config dir under agentDir, mounted into the sandbox
 *  whole, so its bun install is a Linux one and never collides with the host's. */
export function sandboxConfigDir(agentDir: string): string {
  return path.join(agentDir, "sandbox", "opencode");
}

export function sessionsDir(agentDir: string): string {
  return path.join(agentDir, "sessions");
}

export function renameDir(agentDir: string): string {
  return path.join(agentDir, "rename");
}

/** The plugin's filename in a shared plugins dir: unique per repository. */
function pluginName(cwd: string): string {
  return `tet-${crypto.createHash("sha256").update(cwd).digest("hex").slice(0, 16)}.ts`;
}

/**
 * Writes this repository's plugin into `configDir/plugins/` for one target and returns the
 * environment that makes opencode load and scope it. The record directories are created here,
 * since the plugin only ever writes into them. Written beside the target and renamed into
 * place, and only when the content changed — opencode recompiles a changed plugin file, at a
 * cost of seconds to minutes, which is also why nothing per-run (the control channel's port and
 * token) is baked in: the plugin reads those from its own environment.
 */
export function writeOpencodePlugin(
  configDir: string,
  agentDir: string,
  cwd: string,
  contextFile: string,
  target: HookTarget,
  sandbox: string | null
): Record<string, string> {
  const pluginsDir = path.join(configDir, "plugins");
  fs.mkdirSync(pluginsDir, { recursive: true });
  for (const dir of [sessionsDir(agentDir), renameDir(agentDir)]) {
    fs.mkdirSync(dir, { recursive: true });
  }
  const contents = renderOpencodePlugin({
    projectRoot: target.embed(cwd),
    contextFile: target.embed(contextFile),
    sessionsDir: target.embed(sessionsDir(agentDir)),
    renameDir: target.embed(renameDir(agentDir)),
    sandbox
  });
  const file = path.join(pluginsDir, pluginName(cwd));
  let existing: string | undefined;
  try {
    existing = fs.readFileSync(file, "utf8");
  } catch {
    existing = undefined;
  }
  if (existing !== contents) {
    const temp = `${file}.tmp`;
    fs.writeFileSync(temp, contents);
    fs.renameSync(temp, file);
  }
  return { OPENCODE_CONFIG_DIR: target.embed(configDir), [PROJECT_ROOT_ENV]: target.embed(cwd) };
}

/**
 * The plugin's TypeScript source, pure so the test can compile and drive it without opencode.
 * Nothing is imported from opencode's packages — the file must be valid wherever the config dir
 * is — and every path and name is baked in as a JSON literal, never spliced raw.
 */
export function renderOpencodePlugin(options: OpencodePluginOptions): string {
  return `// Generated by tet for one repository, read by nothing but opencode. Turns are reported
// over tet's control channel (src/shared/control.ts); the session records are tet's listing;
// the context file is tet's.
import * as fs from "node:fs";
import * as path from "node:path";
import * as http from "node:http";
import { randomUUID } from "node:crypto";

const PROJECT_ROOT = ${JSON.stringify(options.projectRoot)};
const CONTEXT_FILE = ${JSON.stringify(options.contextFile)};
const SESSIONS_DIR = ${JSON.stringify(options.sessionsDir)};
const RENAME_DIR = ${JSON.stringify(options.renameDir)};
const SANDBOX: string | null = ${JSON.stringify(options.sandbox)};
// The names only: the port and token behind them are new on every start of tet, and a plugin
// file whose contents changed costs opencode a recompile.
const CONTROL = ${JSON.stringify(CONTROL_ENV)};
// A permission opencode approves by itself still raises permission.asked, with the reply
// milliseconds behind it (measured: 7 ms). Held this long before it counts as a question, and
// let go when the reply arrives first.
const PERMISSION_SETTLE_MS = 500;
// How often a rename request left by tet is looked for. Polled, not watched: an inotify watch
// sees nothing written from the other side of a Docker bind mount.
const RENAME_POLL_MS = 1000;
// One question reaches this twice — question.asked and the tool call, milliseconds apart
// (measured). The mark absorbs a repeat but the toast would not, so the second is dropped here.
const WAITING_GAP_MS = 2000;

// Only a session id may become a record's filename.
function isSessionId(id: unknown): id is string {
  return typeof id === "string" && /^[0-9A-Za-z_-]+$/.test(id);
}

// This tab's own turn, reported to tet: the same wire contract tet-ctl speaks, from inside this
// process rather than through it — nothing here needs a process of its own. node:http rather
// than fetch, which is what this file already relies on being there (measured through both
// runtimes opencode ships as). Never awaited: opencode waits for a hook to return, and a turn
// mark must not hold up the TUI.
function report(event: string): void {
  const port = process.env[CONTROL.port];
  const token = process.env[CONTROL.token];
  if (!port || !token) {
    return;
  }
  const body = JSON.stringify({
    token,
    verb: "hook",
    args: { event },
    caller: { projectId: process.env[CONTROL.projectId], tabId: process.env[CONTROL.tabId] }
  });
  try {
    const request = http.request(
      {
        host: process.env[CONTROL.host] || "127.0.0.1",
        port: Number(port),
        method: "POST",
        path: "/",
        headers: { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(body), Connection: "close" }
      },
      (response: any) => response.resume()
    );
    request.on("error", () => undefined);
    request.end(body);
  } catch {
    // Nothing to tell opencode about; a missed report is a tab that has to be looked at.
  }
}

// A reply names its request's id under one of three names, varying across releases.
function permissionKey(props: any): string {
  return [props.id, props.requestID, props.permissionID].find((value) => typeof value === "string") ?? String(props.sessionID);
}

// Written beside the target and renamed into place: tet reads these from another process, and
// on Windows a read landing mid-write fails outright.
function writeRecord(id: string, record: unknown): void {
  try {
    fs.mkdirSync(SESSIONS_DIR, { recursive: true });
    const file = path.join(SESSIONS_DIR, id + ".json");
    fs.writeFileSync(file + ".tmp", JSON.stringify(record));
    fs.renameSync(file + ".tmp", file);
  } catch {
    // As above.
  }
}

export const TETPlugin = async (input: any) => {
  // The host's plugins dir is shared across repositories, so each process loads every
  // repository's plugin; without this guard a message would get every other one's context too.
  const mine = process.env.${PROJECT_ROOT_ENV} === PROJECT_ROOT;
  // Subagent sessions (opencode's task tool) go idle on every turn of theirs and raise questions
  // of their own; the tab is about the root session, so a child's signals are dropped. Children
  // are created here, so their created/updated event precedes any signal of theirs; an id never
  // seen counts as a root.
  const children = new Set<string>();
  const pendingPermissions = new Map<string, ReturnType<typeof setTimeout>>();
  const lastWaiting = new Map<string, number>();

  // Both of opencode's ways of stopping for the user report as \`permission\`: its question tool
  // is one more thing it is blocked on, and the wording tet toasts is the same for both.
  const waiting = (sessionId: unknown): void => {
    if (!isSessionId(sessionId) || children.has(sessionId)) {
      return;
    }
    const now = Date.now();
    if (now - (lastWaiting.get(sessionId) ?? 0) <= WAITING_GAP_MS) {
      return;
    }
    lastWaiting.set(sessionId, now);
    report("permission");
  };

  const onSession = (info: any, deleted: boolean): void => {
    if (!info || !isSessionId(info.id)) {
      return;
    }
    if (typeof info.parentID === "string" && info.parentID.length > 0) {
      children.add(info.id);
      return;
    }
    if (deleted) {
      try {
        fs.rmSync(path.join(SESSIONS_DIR, info.id + ".json"), { force: true });
      } catch {
        // Gone already, or never written.
      }
      return;
    }
    writeRecord(info.id, {
      id: info.id,
      title: typeof info.title === "string" ? info.title : "",
      created: typeof info.time?.created === "number" ? info.time.created : 0,
      updated: typeof info.time?.updated === "number" ? info.time.updated : 0,
      sandbox: SANDBOX
    });
  };

  // A rename tet asked for: a file named after the session, holding the new title. Applied
  // through the server this process already is; session.updated then rewrites the record.
  const applyRenames = async (): Promise<void> => {
    let names: string[];
    try {
      names = fs.readdirSync(RENAME_DIR);
    } catch {
      return;
    }
    for (const id of names) {
      if (!isSessionId(id)) {
        continue;
      }
      const file = path.join(RENAME_DIR, id);
      let title: string;
      try {
        title = fs.readFileSync(file, "utf8").trim();
      } catch {
        continue;
      }
      try {
        if (title) {
          await input.client.session.update({ path: { id }, body: { title } });
        }
      } catch {
        // The session is not this process's to rename; tet's own timeout says so.
      }
      try {
        fs.rmSync(file, { force: true });
      } catch {
        // Picked up again next time, and the update above is idempotent.
      }
    }
  };
  if (mine) {
    setInterval(() => void applyRenames(), RENAME_POLL_MS).unref();
  }

  return {
    "chat.message": async (_input: any, output: any) => {
      if (!mine) return;
      try {
        let text = fs.readFileSync(CONTEXT_FILE, "utf8");
        if (text.charCodeAt(0) === 0xfeff) {
          text = text.slice(1);
        }
        if (text.trim().length > 0) {
          output.parts.push({
            id: "prt_" + randomUUID().replace(/-/g, ""),
            sessionID: output.message.sessionID,
            messageID: output.message.id,
            type: "text",
            text,
            synthetic: true
          });
        }
      } catch {
        // Nothing run in a shell yet — skip silently.
      }
    },
    // The question tool raises question.asked below too; seen here in case that event is renamed.
    "tool.execute.before": async (call: any) => {
      if (mine && call?.tool === "question") {
        waiting(call.sessionID);
      }
    },
    event: async ({ event }: { event: any }) => {
      if (!mine || !event || typeof event.type !== "string") {
        return;
      }
      const props = event.properties ?? {};
      switch (event.type) {
        case "session.created":
        case "session.updated":
          onSession(props.info, false);
          return;
        case "session.deleted":
          onSession(props.info, true);
          return;
        // Raised for every step of a turn — a retry, the next model call — and the mark is
        // simply set again. The other statuses (idle, retry) are not a start. \`prompt-submit\`
        // is what a turn starting is called on the channel; opencode takes the context file
        // itself, in chat.message, so it has no use for what the answer carries.
        case "session.status":
          if (isSessionId(props.sessionID) && !children.has(props.sessionID) && props.status?.type === "busy") {
            report("prompt-submit");
          }
          return;
        // The end of the turn as the tab sees it — also after an error and after an abort
        // (measured), and sometimes twice for one turn, which the mark absorbs.
        case "session.idle":
          if (isSessionId(props.sessionID) && !children.has(props.sessionID)) {
            report("stop");
          }
          return;
        case "permission.asked": {
          const key = permissionKey(props);
          if (pendingPermissions.has(key)) {
            return;
          }
          const timer = setTimeout(() => {
            pendingPermissions.delete(key);
            waiting(props.sessionID);
          }, PERMISSION_SETTLE_MS);
          timer.unref?.();
          pendingPermissions.set(key, timer);
          return;
        }
        case "permission.replied": {
          const key = permissionKey(props);
          const timer = pendingPermissions.get(key);
          if (timer) {
            clearTimeout(timer);
            pendingPermissions.delete(key);
          }
          return;
        }
        case "question.asked":
          waiting(props.sessionID);
          return;
        default:
          return;
      }
    }
  };
};
`;
}
