import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import writeFileAtomic from "write-file-atomic";
import { sandboxHookDir, type HookTarget } from "../../terminals/hook-target";
import { renderHookReport } from "../hook-report";

/**
 * opencode is driven by one generated plugin per repository: a `.ts` under a config dir's
 * `plugins/`, loaded in-process by the tab's `opencode`. There is no declarative hook file; the
 * plugin API is the only way into a message being composed (`chat.message`) and, via the event
 * bus (`event`), to every turn signal. Measured (1.18.4 host, 1.18.23 sbx): `event` receives
 * `session.created`, `session.updated` (whole session), `session.status`, `session.idle`,
 * `permission.asked`/`replied` and `question.asked` exactly as `/event` does.
 *
 * `OPENCODE_CONFIG_DIR` is additive to the user's `plugins/`. On first sight of a plugin in a
 * config dir, opencode bun-installs `@opencode-ai/plugin` *into it* (measured, seconds to
 * minutes) — so the host dir is shared across repositories and a sandbox gets a Linux one. Shared,
 * each repository's plugin needs a unique filename *and* the `TET_PROJECT_ROOT` runtime guard. Never
 * an `opencode.json` in a config dir: it would override the user's.
 */

/** Baked into one repository's plugin; the control channel's address is read from its env. */
export interface OpencodePluginOptions {
  /** The repository root as the plugin's process sees it — the `TET_PROJECT_ROOT` guard. */
  projectRoot: string;
  contextFile: string;
  /** Session records (sessions/<id>.json) and rename requests. */
  sessionsDir: string;
  renameDir: string;
  /** Recorded on every session; null on the host. */
  sandbox: string | null;
}

/** Tells the plugin which repository its process serves. */
export const PROJECT_ROOT_ENV = "TET_PROJECT_ROOT";

/** One session's record under sessionsDir — what the listing reads. */
export interface SessionRecord {
  id: string;
  title: string;
  created: number;
  updated: number;
  sandbox: string | null;
}

/** A sandboxed tab's config dir under agentDir, mounted whole: its bun install is Linux's own. */
export function sandboxConfigDir(agentDir: string): string {
  return path.join(sandboxHookDir(agentDir), "opencode");
}

export function sessionsDir(agentDir: string): string {
  return path.join(agentDir, "sessions");
}

export function renameDir(agentDir: string): string {
  return path.join(agentDir, "rename");
}

/** Unique per repository in a shared plugins dir. */
function pluginName(cwd: string): string {
  return `tet-${crypto.createHash("sha256").update(cwd).digest("hex").slice(0, 16)}.ts`;
}

/**
 * Writes the repository's plugin into `configDir/plugins/`; returns the env that loads and scopes
 * it. Creates the record directories. Renamed into place, and only when changed — opencode
 * recompiles a changed plugin (seconds to minutes), so nothing per-run (control port, token) is
 * baked in.
 */
export function writeOpencodePlugin(
  configDir: string,
  agentDir: string,
  cwd: string,
  contextFile: string,
  target: HookTarget,
  sandbox: string | null
): Record<string, string> {
  const pluginsDir = path.join(configDir, "plugins");
  fs.mkdirSync(pluginsDir, { recursive: true });
  for (const dir of [sessionsDir(agentDir), renameDir(agentDir)]) {
    fs.mkdirSync(dir, { recursive: true });
  }
  const contents = renderOpencodePlugin({
    projectRoot: target.embed(cwd),
    contextFile: target.embed(contextFile),
    sessionsDir: target.embed(sessionsDir(agentDir)),
    renameDir: target.embed(renameDir(agentDir)),
    sandbox
  });
  const file = path.join(pluginsDir, pluginName(cwd));
  let existing: string | undefined;
  try {
    existing = fs.readFileSync(file, "utf8");
  } catch {
    existing = undefined;
  }
  if (existing !== contents) {
    writeFileAtomic.sync(file, contents);
  }
  return { OPENCODE_CONFIG_DIR: target.embed(configDir), [PROJECT_ROOT_ENV]: target.embed(cwd) };
}

/**
 * The plugin source; pure, so tests drive it without opencode. Imports nothing from opencode's
 * packages (valid in any config dir); values are baked in as JSON literals, never spliced raw.
 */
export function renderOpencodePlugin(options: OpencodePluginOptions): string {
  return `// Generated by tet for one repository, read by nothing but opencode. Turns are reported
// over tet's control channel (src/shared/control.ts); the session records are tet's listing;
// the context file is tet's.
import * as fs from "node:fs";
import * as path from "node:path";
import * as http from "node:http";
import { randomUUID } from "node:crypto";

const PROJECT_ROOT = ${JSON.stringify(options.projectRoot)};
const CONTEXT_FILE = ${JSON.stringify(options.contextFile)};
const SESSIONS_DIR = ${JSON.stringify(options.sessionsDir)};
const RENAME_DIR = ${JSON.stringify(options.renameDir)};
const SANDBOX: string | null = ${JSON.stringify(options.sandbox)};
// A permission opencode approves by itself still raises permission.asked, with the reply
// milliseconds behind it (measured: 7 ms). Held this long before it counts as a question, and
// let go when the reply arrives first.
const PERMISSION_SETTLE_MS = 500;
// How often a rename request left by tet is looked for. Polled, not watched: an inotify watch
// sees nothing written from the other side of a Docker bind mount.
const RENAME_POLL_MS = 1000;
// One question reaches this twice — question.asked and the tool call, milliseconds apart
// (measured). The mark absorbs a repeat but the toast would not, so the second is dropped here.
const WAITING_GAP_MS = 2000;

// Only a session id may become a record's filename.
function isSessionId(id: unknown): id is string {
  return typeof id === "string" && /^[0-9A-Za-z_-]+$/.test(id);
}

${renderHookReport("opencode")}

// A reply names its request's id under one of three names, varying across releases.
function permissionKey(props: any): string {
  return [props.id, props.requestID, props.permissionID].find((value) => typeof value === "string") ?? String(props.sessionID);
}

// Written beside the target and renamed into place: tet reads these from another process, and
// on Windows a read landing mid-write fails outright.
function writeRecord(id: string, record: unknown): void {
  try {
    fs.mkdirSync(SESSIONS_DIR, { recursive: true });
    const file = path.join(SESSIONS_DIR, id + ".json");
    fs.writeFileSync(file + ".tmp", JSON.stringify(record));
    fs.renameSync(file + ".tmp", file);
  } catch {
    // As above.
  }
}

export const TETPlugin = async (input: any) => {
  // The host's plugins dir is shared across repositories, so each process loads every
  // repository's plugin; without this guard a message would get every other one's context too.
  const mine = process.env.${PROJECT_ROOT_ENV} === PROJECT_ROOT;
  // Subagent sessions (opencode's task tool) go idle on every turn of theirs and raise questions
  // of their own; the tab is about the root session, so a child's signals are dropped. Children
  // are created here, so their created/updated event precedes any signal of theirs; an id never
  // seen counts as a root.
  const children = new Set<string>();
  const pendingPermissions = new Map<string, ReturnType<typeof setTimeout>>();
  // Permissions that got as far as a question mark, so their reply knows to take it away again.
  const markedPermissions = new Set<string>();
  const lastWaiting = new Map<string, number>();

  // Both of opencode's ways of stopping for the user report as \`permission\`: its question tool
  // is one more thing it is blocked on, and the wording tet toasts is the same for both. Answers
  // whether this tab now has a question standing — a repeat inside the gap counts, since the one
  // reported a moment ago is still there.
  const waiting = (sessionId: unknown): boolean => {
    if (!isSessionId(sessionId) || children.has(sessionId)) {
      return false;
    }
    const now = Date.now();
    if (now - (lastWaiting.get(sessionId) ?? 0) > WAITING_GAP_MS) {
      lastWaiting.set(sessionId, now);
      report("permission", sessionId);
    }
    return true;
  };

  const onSession = (info: any, deleted: boolean): void => {
    if (!info || !isSessionId(info.id)) {
      return;
    }
    if (typeof info.parentID === "string" && info.parentID.length > 0) {
      children.add(info.id);
      return;
    }
    if (deleted) {
      try {
        fs.rmSync(path.join(SESSIONS_DIR, info.id + ".json"), { force: true });
      } catch {
        // Gone already, or never written.
      }
      return;
    }
    writeRecord(info.id, {
      id: info.id,
      title: typeof info.title === "string" ? info.title : "",
      created: typeof info.time?.created === "number" ? info.time.created : 0,
      updated: typeof info.time?.updated === "number" ? info.time.updated : 0,
      sandbox: SANDBOX
    });
  };

  // A rename tet asked for: a file named after the session, holding the new title. Applied
  // through the server this process already is; session.updated then rewrites the record.
  const applyRenames = async (): Promise<void> => {
    let names: string[];
    try {
      names = fs.readdirSync(RENAME_DIR);
    } catch {
      return;
    }
    for (const id of names) {
      if (!isSessionId(id)) {
        continue;
      }
      const file = path.join(RENAME_DIR, id);
      let title: string;
      try {
        title = fs.readFileSync(file, "utf8").trim();
      } catch {
        continue;
      }
      // Every opencode of the repository polls this one folder, a sandboxed one included, and only
      // the process whose database holds the session can apply it: a request another process could
      // not apply is left for that one, and withdrawn by tet's own timeout when there is none.
      let applied = !title;
      try {
        if (title) {
          // The client answers an unknown session with an error rather than throwing, unless told to.
          const result = await input.client.session.update({ path: { id }, body: { title } });
          applied = !result?.error;
        }
      } catch {
        // As above: not this process's session.
      }
      if (!applied) {
        continue;
      }
      try {
        fs.rmSync(file, { force: true });
      } catch {
        // Picked up again next time, and the update above is idempotent.
      }
    }
  };
  if (mine) {
    setInterval(() => void applyRenames(), RENAME_POLL_MS).unref();
  }

  return {
    "chat.message": async (_input: any, output: any) => {
      if (!mine) return;
      // The turn starts here, once, the way it does for every other agent tet drives: a prompt
      // was submitted. Not from session.status, which is raised again for every step of the turn
      // — twenty tool calls used to be twenty reports, each ~100 ms on the way out of a sandbox,
      // and the last of them raced its own turn's session.idle. The mark is a state, not a
      // pulse: once set it stands until the end of the turn reports.
      const sessionId = output?.message?.sessionID;
      if (!children.has(String(sessionId))) {
        report("prompt-submit", isSessionId(sessionId) ? sessionId : undefined);
      }
      try {
        let text = fs.readFileSync(CONTEXT_FILE, "utf8");
        if (text.charCodeAt(0) === 0xfeff) {
          text = text.slice(1);
        }
        if (text.trim().length > 0) {
          output.parts.push({
            id: "prt_" + randomUUID().replace(/-/g, ""),
            sessionID: output.message.sessionID,
            messageID: output.message.id,
            type: "text",
            text,
            synthetic: true
          });
        }
      } catch {
        // Nothing run in a shell yet — skip silently.
      }
    },
    // The question tool raises question.asked below too; seen here in case that event is renamed.
    "tool.execute.before": async (call: any) => {
      if (mine && call?.tool === "question") {
        waiting(call.sessionID);
      }
    },
    event: async ({ event }: { event: any }) => {
      if (!mine || !event || typeof event.type !== "string") {
        return;
      }
      const props = event.properties ?? {};
      switch (event.type) {
        case "session.created":
        case "session.updated":
          onSession(props.info, false);
          return;
        case "session.deleted":
          onSession(props.info, true);
          return;
        // The end of the turn as the tab sees it — also after an error and after an abort
        // (measured), and sometimes twice for one turn, which the mark absorbs.
        case "session.idle":
          if (isSessionId(props.sessionID) && !children.has(props.sessionID)) {
            report("stop", props.sessionID);
          }
          return;
        case "permission.asked": {
          const key = permissionKey(props);
          if (pendingPermissions.has(key)) {
            return;
          }
          const timer = setTimeout(() => {
            pendingPermissions.delete(key);
            if (waiting(props.sessionID)) {
              markedPermissions.add(key);
            }
          }, PERMISSION_SETTLE_MS);
          timer.unref?.();
          pendingPermissions.set(key, timer);
          return;
        }
        case "permission.replied": {
          const key = permissionKey(props);
          const timer = pendingPermissions.get(key);
          if (timer) {
            clearTimeout(timer);
            pendingPermissions.delete(key);
          }
          // One that did stand as a question is answered now, by whoever — opencode itself where
          // its own approval took longer than the settle above. The session is working again, and
          // saying so is what takes the mark away; nothing else would until the turn ended.
          if (markedPermissions.delete(key)) {
            report("prompt-submit", isSessionId(props.sessionID) ? props.sessionID : undefined);
          }
          return;
        }
        case "question.asked":
          waiting(props.sessionID);
          return;
        default:
          return;
      }
    }
  };
};
`;
}
